
import Connection.DbHandler;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class Addingmarks extends javax.swing.JFrame {

    /**
     * Creates new form Addingmarks
     */
    public Addingmarks() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addstdID = new javax.swing.JTextField();
        addstdIDFinal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addsubCode = new javax.swing.JTextField();
        addSubcodeFinal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addgrade = new javax.swing.JTextField();
        addGradeFinal = new javax.swing.JTextField();
        addassignmntNO = new javax.swing.JTextField();
        addassignmntType = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        FinalADD = new javax.swing.JButton();
        FinalUpdate = new javax.swing.JButton();
        DelAssignMarksButton = new javax.swing.JButton();
        AssignmentUpdate = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        delstdIDAssignmnt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AssignmentADD = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        delstdIDFinal = new javax.swing.JTextField();
        DelFinalMarkButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        delassignmntNO = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        delsubCodeFinal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        addsemidFinal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelHomeback = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Assignment marks");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Final marks");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student ID");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student ID");

        addstdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstdIDActionPerformed(evt);
            }
        });

        addstdIDFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstdIDFinalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Subject Code");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Subject Code");

        addsubCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsubCodeActionPerformed(evt);
            }
        });

        addSubcodeFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubcodeFinalActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Grade");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Grade");

        addgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgradeActionPerformed(evt);
            }
        });

        addGradeFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGradeFinalActionPerformed(evt);
            }
        });

        addassignmntNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addassignmntNOActionPerformed(evt);
            }
        });

        addassignmntType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addassignmntTypeActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Assignment type");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Assignment No");

        FinalADD.setBackground(new java.awt.Color(255, 255, 255));
        FinalADD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FinalADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_30px.png"))); // NOI18N
        FinalADD.setText("ADD");
        FinalADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalADDActionPerformed(evt);
            }
        });

        FinalUpdate.setBackground(new java.awt.Color(255, 255, 255));
        FinalUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FinalUpdate.setText("Update");
        FinalUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalUpdateActionPerformed(evt);
            }
        });

        DelAssignMarksButton.setBackground(new java.awt.Color(255, 255, 255));
        DelAssignMarksButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DelAssignMarksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px_1.png"))); // NOI18N
        DelAssignMarksButton.setText("Delete");
        DelAssignMarksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelAssignMarksButtonActionPerformed(evt);
            }
        });

        AssignmentUpdate.setBackground(new java.awt.Color(255, 255, 255));
        AssignmentUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AssignmentUpdate.setText("Update");
        AssignmentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentUpdateActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Delete Assignment marks");

        delstdIDAssignmnt.setBackground(new java.awt.Color(204, 204, 204));
        delstdIDAssignmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delstdIDAssignmntActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Student ID");

        AssignmentADD.setBackground(new java.awt.Color(255, 255, 255));
        AssignmentADD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AssignmentADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_30px.png"))); // NOI18N
        AssignmentADD.setText("ADD");
        AssignmentADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentADDActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Delete Final marks");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Student ID");

        delstdIDFinal.setBackground(new java.awt.Color(204, 204, 204));
        delstdIDFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delstdIDFinalActionPerformed(evt);
            }
        });

        DelFinalMarkButton.setBackground(new java.awt.Color(255, 255, 255));
        DelFinalMarkButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DelFinalMarkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px_1.png"))); // NOI18N
        DelFinalMarkButton.setText("Delete");
        DelFinalMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelFinalMarkButtonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Assignment No");

        delassignmntNO.setBackground(new java.awt.Color(204, 204, 204));
        delassignmntNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delassignmntNOActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Subject Code");

        delsubCodeFinal.setBackground(new java.awt.Color(204, 204, 204));
        delsubCodeFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delsubCodeFinalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Semester");

        addsemidFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsemidFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addsubCode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AssignmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(AssignmentADD, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(219, 219, 219))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel27)
                        .addGap(33, 33, 33)
                        .addComponent(delstdIDFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(delsubCodeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(DelFinalMarkButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addassignmntNO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(addstdID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(addassignmntType, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(27, 27, 27)
                        .addComponent(delstdIDAssignmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(delassignmntNO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(DelAssignMarksButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addstdIDFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(addSubcodeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel18))
                            .addComponent(addsemidFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FinalADD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FinalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addGradeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(308, 308, 308)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(delstdIDAssignmnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(delassignmntNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelAssignMarksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(addstdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(addsubCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(addgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addassignmntNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addassignmntType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignmentADD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(delstdIDFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(delsubCodeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelFinalMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addstdIDFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(addSubcodeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(addGradeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(addsemidFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FinalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FinalADD))))
                .addGap(264, 264, 264))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 900, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabelHomeback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHomeback.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_Back_30px.png"))); // NOI18N
        jLabelHomeback.setText("Back");
        jLabelHomeback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomebackMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maintain Marks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelHomeback, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(jLabel3)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomebackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomebackMouseClicked
        Studentsmanage Stdmanage = new Studentsmanage();
        Stdmanage.setVisible(true);
        Stdmanage.pack();
        Stdmanage.setLocationRelativeTo(null);
        Stdmanage.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHomebackMouseClicked

    private void addstdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addstdIDActionPerformed

    private void addstdIDFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstdIDFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addstdIDFinalActionPerformed

    private void addsubCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsubCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addsubCodeActionPerformed

    private void addSubcodeFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubcodeFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSubcodeFinalActionPerformed

    private void addgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addgradeActionPerformed

    private void addGradeFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradeFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addGradeFinalActionPerformed

    private void addassignmntNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addassignmntNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addassignmntNOActionPerformed

    private void addassignmntTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addassignmntTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addassignmntTypeActionPerformed

    private void FinalUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalUpdateActionPerformed

        String StudentID = addstdIDFinal.getText();
        String subcode = addSubcodeFinal.getText();
        String grade = addGradeFinal.getText();
        String semid=addsemidFinal.getText();

        try {

            DbHandler.setData("UPDATE grup_project.finalsemmarks SET subcode='" + subcode + "',grade='" + grade + "',semester='" + semid + "'WHERE sid='" + StudentID + "'");

            JOptionPane.showMessageDialog(null, "Values Successfuly Updated");
        } catch (SQLException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        addstdIDFinal.setText(null);
        addSubcodeFinal.setText(null);
        addGradeFinal.setText(null);
        addsemidFinal.setText(null);


    }//GEN-LAST:event_FinalUpdateActionPerformed
//function for update assignment
    private void AssignmentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentUpdateActionPerformed
        String StudentID = addstdID.getText();
        String subcode = addsubCode.getText();
        String grade = addgrade.getText();
        String assubcodesignmentno = addassignmntNO.getText();
        String assignmenttype = addassignmntType.getText();

        try {

            DbHandler.setData("UPDATE grup_project.assignment SET subcode='" + subcode + "',grade='" + grade + "',assignmntno='" + assubcodesignmentno + "',typeofassignmnt='" + assignmenttype + "'WHERE sid='" + StudentID + "'");

            JOptionPane.showMessageDialog(null, "Values Successfuly Updated");
        } catch (SQLException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        addstdID.setText(null);
        addsubCode.setText(null);
        addgrade.setText(null);
        addassignmntNO.setText(null);
        addassignmntType.setText(null);


    }//GEN-LAST:event_AssignmentUpdateActionPerformed
//Function for Delete assignments
    private void DelAssignMarksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelAssignMarksButtonActionPerformed
        String StudentID = delstdIDAssignmnt.getText();
        String assignmentno = delassignmntNO.getText();

        try {

            DbHandler.setData("DELETE FROM grup_project.assignment where sid='" + StudentID + "' and assignmntno= '" + assignmentno + "'");

            JOptionPane.showMessageDialog(null, "Values successfuly Deleted");

        } catch (SQLException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        delstdIDAssignmnt.setText(null);
        delassignmntNO.setText(null);


    }//GEN-LAST:event_DelAssignMarksButtonActionPerformed

    private void FinalADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalADDActionPerformed
        String StudentID = addstdIDFinal.getText();
        String subcode = addSubcodeFinal.getText();
        String grade = addGradeFinal.getText();
        String semid=addsemidFinal.getText();

        try {

            if (addstdIDFinal.getText().isEmpty() || addSubcodeFinal.getText().isEmpty() || addGradeFinal.getText().isEmpty()||addsemidFinal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Insert values");

            } else {
                DbHandler.setData("INSERT INTO grup_project.finalsemmarks(sid,subcode,grade,semester) values('" + StudentID + "','" + subcode + "','" + grade + "','"+semid+"')");

                JOptionPane.showMessageDialog(null, "Values successfuly Inserted");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        addstdIDFinal.setText(null);
        addSubcodeFinal.setText(null);
        addGradeFinal.setText(null);
        addsemidFinal.setText(null);


    }//GEN-LAST:event_FinalADDActionPerformed

    private void delstdIDAssignmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delstdIDAssignmntActionPerformed

    }//GEN-LAST:event_delstdIDAssignmntActionPerformed

    private void AssignmentADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentADDActionPerformed
        String StudentID = addstdID.getText();
        String subcode = addsubCode.getText();
        String grade = addgrade.getText();
        String assignmentno = addassignmntNO.getText();
        String assignmenttype = addassignmntType.getText();

        try {

            if (addassignmntType.getText().isEmpty() || addstdID.getText().isEmpty() || addsubCode.getText().isEmpty() || addgrade.getText().isEmpty() || addassignmntNO.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Insert values");

            } else {
                DbHandler.setData("INSERT INTO grup_project.assignment(sid,subcode,assignmntno,grade,typeofassignmnt) values('" + StudentID + "','" + subcode + "','" + assignmentno + "','" + grade + "','" + assignmenttype + "')");

                JOptionPane.showMessageDialog(null, "Values successfuly Inserted");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        addstdID.setText(null);
        addgrade.setText(null);
        addsubCode.setText(null);
        addassignmntType.setText(null);
        addassignmntNO.setText(null);

        // TODO add your handling code here:

    }//GEN-LAST:event_AssignmentADDActionPerformed

    private void delstdIDFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delstdIDFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delstdIDFinalActionPerformed
//Delete Final marks Function
    private void DelFinalMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelFinalMarkButtonActionPerformed
        String StudentID = delstdIDFinal.getText();
        String subcode = delsubCodeFinal.getText();

        try {

            DbHandler.setData(" DELETE  FROM grup_project.finalsemmarks where sid='" + StudentID + "'AND subcode='" + subcode + "' ");

            JOptionPane.showMessageDialog(null, "Values successfuly Deleted");

            delstdIDFinal.setText(null);
            delsubCodeFinal.setText(null);

        } catch (SQLException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Addingmarks.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DelFinalMarkButtonActionPerformed

    private void delassignmntNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delassignmntNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delassignmntNOActionPerformed

    private void delsubCodeFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delsubCodeFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delsubCodeFinalActionPerformed

    private void addsemidFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsemidFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addsemidFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addingmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addingmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addingmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addingmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addingmarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignmentADD;
    private javax.swing.JButton AssignmentUpdate;
    private javax.swing.JButton DelAssignMarksButton;
    private javax.swing.JButton DelFinalMarkButton;
    private javax.swing.JButton FinalADD;
    private javax.swing.JButton FinalUpdate;
    private javax.swing.JTextField addGradeFinal;
    private javax.swing.JTextField addSubcodeFinal;
    private javax.swing.JTextField addassignmntNO;
    private javax.swing.JTextField addassignmntType;
    private javax.swing.JTextField addgrade;
    private javax.swing.JTextField addsemidFinal;
    private javax.swing.JTextField addstdID;
    private javax.swing.JTextField addstdIDFinal;
    private javax.swing.JTextField addsubCode;
    private javax.swing.JTextField delassignmntNO;
    private javax.swing.JTextField delstdIDAssignmnt;
    private javax.swing.JTextField delstdIDFinal;
    private javax.swing.JTextField delsubCodeFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHomeback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
