
import Connection.DbHandler;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.UserLogin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class Adminlogin extends javax.swing.JFrame {

    /**
     * Creates new form StaffLogin
     */
    public Adminlogin() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUsername = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel7.setMinimumSize(new java.awt.Dimension(400, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NSBM STUDENTS MANAGEMENT SYSTEM");

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Exit_30px_1.png"))); // NOI18N
        jLabelExit.setText("Exit");
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nsbm1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 430, 105, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Username :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(210, 380, 105, 31);

        jPassword.setBackground(new java.awt.Color(153, 153, 153));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(jPassword);
        jPassword.setBounds(340, 430, 227, 31);

        jUsername.setBackground(new java.awt.Color(153, 153, 153));
        jUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(jUsername);
        jUsername.setBounds(340, 380, 227, 31);

        jLoginButton.setBackground(new java.awt.Color(34, 167, 240));
        jLoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        jLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_30px_1.png"))); // NOI18N
        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jLoginButton);
        jLoginButton.setBounds(370, 480, 165, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 355, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ADMIN LOGIN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 320, 144, 25);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Campus Stuff\\Assignment\\cap.jpg")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validate_stafflogin(String username, String password) {
        try {
     //  Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            //  Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javademo?" + "user=root&password=");     
            //  PreparedStatement pst = conn.prepareStatement("Select * from login where username=? and password=?");
            //   pst.setString(1, username); 
            //   pst.setString(2, password);
            String query = "SELECT * FROM grup_project.user_login WHERE username='" + username + "' AND password='" + password + "' ";
            ResultSet rs = DbHandler.getData(query);
            if (rs.next()) {
                return true;
            } else {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        if (jUsername.getText().length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        } else if (jPassword.getPassword().length == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        } else {
            String user = jUsername.getText();   // Collecting the input
            char[] pass = jPassword.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            String query = "SELECT * FROM grup_project.user_login WHERE username='" + user + "' AND password='" + pwd + "' ";
            ResultSet rs;
            String facultyname;
            String studentid = null;
            try {
                rs = DbHandler.getData(query);
                while (rs.next()) {
                    studentid = rs.getString("id");
                    UserLogin.id = studentid;

                    facultyname = rs.getString("facultyname");
                    UserLogin.facultyname = facultyname;
                }
                if (validate_stafflogin(user, pwd)) {
                    JOptionPane.showMessageDialog(null, "Correct Login Credentials");

                    Homef st = new Homef();
                    st.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Login");

                }

            } catch (SQLException ex) {
                Logger.getLogger(Adminlogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Adminlogin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jUsername.getText().length() == 0) // Checking for empty field
            {
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
            } else if (jPassword.getPassword().length == 0) // Checking for empty field
            {
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
            } else {
                String user = jUsername.getText();   // Collecting the input
                char[] pass = jPassword.getPassword(); // Collecting the input
                String pwd = String.copyValueOf(pass);  // converting from array to string
                String query = "SELECT * FROM grup_project.user_login WHERE username='" + user + "' AND password='" + pwd + "' ";
                ResultSet rs;
                String facultyname;
                String studentid = null;
                try {
                    rs = DbHandler.getData(query);
                    while (rs.next()) {
                        studentid = rs.getString("id");
                        UserLogin.id = studentid;

                        facultyname = rs.getString("facultyname");
                        UserLogin.facultyname = facultyname;
                    }
                    if (validate_stafflogin(user, pwd)) {
                        JOptionPane.showMessageDialog(null, "Correct Login Credentials");

                        Homef st = new Homef();
                        st.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Login");

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Adminlogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Adminlogin.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
