
import Connection.DbHandler;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class InstructorRegistration extends javax.swing.JFrame {

    /**
     * Creates new form InstructorRegistratin
     */
    public InstructorRegistration() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    boolean Validation_Material() {

        /* if (Integer.parseInt(jTextField5.getText()) == 0){
         JOptionPane.showMessageDialog(null,"Please Insert a valid Number");
         jTextField5.setText(null);
                
         return false;
         }*/
        if (InstID.getText().isEmpty() || InstFname.getText().isEmpty() || InstEmail.getText().isEmpty() || InstQualification.getText().isEmpty() || InstNIC.getText().isEmpty() || InstAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Insert values");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        InstID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InstEmail = new javax.swing.JTextField();
        InstFname = new javax.swing.JTextField();
        jCheckBoxMale = new javax.swing.JCheckBox();
        jCheckBoxFemale = new javax.swing.JCheckBox();
        InstNIC = new javax.swing.JTextField();
        InstQualification = new javax.swing.JTextField();
        jButtonNextreg = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InstAddress = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        upload = new javax.swing.JButton();
        InstContactno = new javax.swing.JTextField();
        uploadfile = new javax.swing.JLabel();
        InstLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jLabelHomeback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Last Name  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 190, 90, 31));

        InstID.setBackground(new java.awt.Color(153, 153, 153));
        InstID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstIDActionPerformed(evt);
            }
        });
        jPanel2.add(InstID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 193, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*Instructor ID  ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 74, -1, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qualification");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*NIC No     ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 398, -1, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Gender       ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 31));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("*Contact No  ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 330, 117, 31));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address    ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BASIC INFORMATION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, 213, -1));

        InstEmail.setBackground(new java.awt.Color(153, 153, 153));
        InstEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstEmailActionPerformed(evt);
            }
        });
        jPanel2.add(InstEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 193, -1));

        InstFname.setBackground(new java.awt.Color(153, 153, 153));
        InstFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstFnameActionPerformed(evt);
            }
        });
        jPanel2.add(InstFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 193, -1));

        jCheckBoxMale.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxMale.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMale.setText("Male");
        jCheckBoxMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMaleActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 64, 31));

        jCheckBoxFemale.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxFemale.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFemale.setText("Female");
        jCheckBoxFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 81, 31));

        InstNIC.setBackground(new java.awt.Color(153, 153, 153));
        InstNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstNICActionPerformed(evt);
            }
        });
        jPanel2.add(InstNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 397, 200, 31));

        InstQualification.setBackground(new java.awt.Color(153, 153, 153));
        InstQualification.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstQualificationActionPerformed(evt);
            }
        });
        jPanel2.add(InstQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 193, 31));

        jButtonNextreg.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNextreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNextreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_30px.png"))); // NOI18N
        jButtonNextreg.setText("Submit");
        jButtonNextreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextregMouseClicked(evt);
            }
        });
        jButtonNextreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextregActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNextreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Email        ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 31));

        InstAddress.setColumns(20);
        InstAddress.setRows(5);
        jScrollPane1.setViewportView(InstAddress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 199, 82));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 67, -1, -1));

        upload.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        upload.setText("Upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel2.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 215, 90, 41));

        InstContactno.setBackground(new java.awt.Color(153, 153, 153));
        InstContactno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstContactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstContactnoActionPerformed(evt);
            }
        });
        jPanel2.add(InstContactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 329, 200, 31));
        jPanel2.add(uploadfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 67, 78, 180));

        InstLname.setBackground(new java.awt.Color(153, 153, 153));
        InstLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstLnameActionPerformed(evt);
            }
        });
        jPanel2.add(InstLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 193, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*First Name  ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 130, -1, 31));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 930, 580));

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTRUCTOR REGISTRATION FORM");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMini.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMini.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMini.setText("-");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });

        jLabelHomeback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHomeback.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_Back_30px.png"))); // NOI18N
        jLabelHomeback.setText("Back");
        jLabelHomeback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomebackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeback, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabelMini)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMini)
                            .addComponent(jLabelClose)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelHomeback)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 924, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstIDActionPerformed

    private void InstEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstEmailActionPerformed

    private void InstFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstFnameActionPerformed

    private void jCheckBoxMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMaleActionPerformed

        if (jCheckBoxMale.isSelected() == true) // if check box is checked
        {
            jCheckBoxFemale.setSelected(false);  // button will enable
            //btnOne.setText("Hi im enabled");// button text will change into parameter msg..
        }
    }//GEN-LAST:event_jCheckBoxMaleActionPerformed

    private void jCheckBoxFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFemaleActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxFemale.isSelected() == true) // if check box is checked
        {
            jCheckBoxMale.setSelected(false);  // button will enable
            //btnOne.setText("Hi im enabled");// button text will change into parameter msg..
        }
    }//GEN-LAST:event_jCheckBoxFemaleActionPerformed

    private void InstNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstNICActionPerformed

    private void InstQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstQualificationActionPerformed

    private void jButtonNextregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextregMouseClicked
        Staffmanage acc = new Staffmanage();
        acc.setVisible(true);
        acc.pack();
        acc.setLocationRelativeTo(null);
        acc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonNextregMouseClicked

    private void jButtonNextregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextregActionPerformed
        // TODO add your handling code here:
        String insid = InstID.getText();
        String FirstName = InstLname.getText();
        String LastName = InstFname.getText();
        String nic = InstEmail.getText();
        String gender = "Male";
        if (jCheckBoxFemale.isSelected() == true) {
            gender = "Female";
        }

        String qualification = InstQualification.getText();
        String contact = InstContactno.getText();
        String email = InstNIC.getText();
        String address = InstAddress.getText();
        //String img= uploadfile.getText();

        try {

            if (Validation_Material() == true) {
                DbHandler.setData("INSERT INTO grup_project.instructors(insID,insFName,insLName,insEmail,insgender,insQualifications,inscontact,insnic,insaddress) values('" + insid + "','" + FirstName + "','" + LastName + "','" + nic + "','" + gender + "','" + qualification + "','" + contact + "','" + email + "','" + address + "')");

                JOptionPane.showMessageDialog(null, "Values successfuly Inserted");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        InstLname.setText(null);
        InstID.setText(null);
        InstFname.setText(null);
        InstEmail.setText(null);
        InstQualification.setText(null);
        InstNIC.setText(null);
        InstAddress.setText(null);

    }//GEN-LAST:event_jButtonNextregActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            //uploadfile.setIcon(ResizeImage(path));

            /*    try {
             FileInputStream fin = new FileInputStream(selectedFile);
             DbHandler.setData("INSERT INTO grup_project.student(image)values('"+fin+"')");

             JOptionPane.showMessageDialog(null,"Values successfuly Inserted");
             } catch (FileNotFoundException ex) {
             Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
             Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
             Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
             }*/
        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }

    }//GEN-LAST:event_uploadActionPerformed

    private void InstContactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstContactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstContactnoActionPerformed

    private void InstLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstLnameActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jLabelHomebackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomebackMouseClicked
        Staffmanage hm = new Staffmanage();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHomebackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InstAddress;
    private javax.swing.JTextField InstContactno;
    private javax.swing.JTextField InstEmail;
    private javax.swing.JTextField InstFname;
    private javax.swing.JTextField InstID;
    private javax.swing.JTextField InstLname;
    private javax.swing.JTextField InstNIC;
    private javax.swing.JTextField InstQualification;
    private javax.swing.JButton jButtonNextreg;
    private javax.swing.JCheckBox jCheckBoxFemale;
    private javax.swing.JCheckBox jCheckBoxMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHomeback;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton upload;
    private javax.swing.JLabel uploadfile;
    // End of variables declaration//GEN-END:variables
}
