
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import javax.swing.JOptionPane;
import Connection.DbHandler;
import java.awt.Dimension;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class LecturerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form StaffRegistration
     */
    public LecturerRegistration() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    boolean Validation_Material() {

        
        if (lectID.getText().isEmpty() || LectLname.getText().isEmpty() || LectEmail.getText().isEmpty() || LectQualification.getText().isEmpty() || LectNIC.getText().isEmpty() || LectAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Insert values");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jLabelHomeback = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lectID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LectEmail = new javax.swing.JTextField();
        LectLname = new javax.swing.JTextField();
        jCheckBoxMale = new javax.swing.JCheckBox();
        jCheckBoxFemale = new javax.swing.JCheckBox();
        LectNIC = new javax.swing.JTextField();
        LectQualification = new javax.swing.JTextField();
        jButtonNextreg = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LectAddress = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        upload = new javax.swing.JButton();
        LectContact = new javax.swing.JTextField();
        uploadfile = new javax.swing.JLabel();
        LectFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LECTURER REGISTRATION FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 32, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabelMini.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMini.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMini.setText("-");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabelHomeback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHomeback.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_Back_30px.png"))); // NOI18N
        jLabelHomeback.setText("Back");
        jLabelHomeback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomebackMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelHomeback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 77, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Last Name  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 31));

        lectID.setBackground(new java.awt.Color(153, 153, 153));
        lectID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lectID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectIDActionPerformed(evt);
            }
        });
        jPanel2.add(lectID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 193, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*Lecture ID  ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qualification");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 348, 117, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*NIC No     ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Gender       ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 31));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("*Contact No  ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 100, 31));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address    ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 406, -1, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BASIC INFORMATION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 22, 213, -1));

        LectEmail.setBackground(new java.awt.Color(153, 153, 153));
        LectEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectEmailActionPerformed(evt);
            }
        });
        jPanel2.add(LectEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 193, -1));

        LectLname.setBackground(new java.awt.Color(153, 153, 153));
        LectLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectLnameActionPerformed(evt);
            }
        });
        jPanel2.add(LectLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 193, -1));

        jCheckBoxMale.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxMale.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMale.setText("Male");
        jCheckBoxMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMaleActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 64, 31));

        jCheckBoxFemale.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxFemale.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFemale.setText("Female");
        jCheckBoxFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 81, 31));

        LectNIC.setBackground(new java.awt.Color(153, 153, 153));
        LectNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectNICActionPerformed(evt);
            }
        });
        jPanel2.add(LectNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 331, 200, 31));

        LectQualification.setBackground(new java.awt.Color(153, 153, 153));
        LectQualification.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectQualificationActionPerformed(evt);
            }
        });
        jPanel2.add(LectQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 347, 199, 31));

        jButtonNextreg.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNextreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNextreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_30px.png"))); // NOI18N
        jButtonNextreg.setText("Submit");
        jButtonNextreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextregMouseClicked(evt);
            }
        });
        jButtonNextreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextregActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNextreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Email        ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 31));

        LectAddress.setColumns(20);
        LectAddress.setRows(5);
        jScrollPane1.setViewportView(LectAddress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 199, 82));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 64, -1, -1));

        upload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        upload.setText("Upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel2.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 108, 87, 31));

        LectContact.setBackground(new java.awt.Color(153, 153, 153));
        LectContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectContactActionPerformed(evt);
            }
        });
        jPanel2.add(LectContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 241, 200, 31));
        jPanel2.add(uploadfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 67, 141, 132));

        LectFname.setBackground(new java.awt.Color(153, 153, 153));
        LectFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LectFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectFnameActionPerformed(evt);
            }
        });
        jPanel2.add(LectFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 193, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*First Name  ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 31));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jLabelHomebackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomebackMouseClicked
        Staffmanage hm = new Staffmanage();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHomebackMouseClicked

    private void lectIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectIDActionPerformed

    private void LectEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectEmailActionPerformed

    private void LectLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectLnameActionPerformed

    private void jCheckBoxMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMaleActionPerformed

        if (jCheckBoxMale.isSelected() == true) // if check box is checked
        {
            jCheckBoxFemale.setSelected(false);  // button will enable
            
        }

    }//GEN-LAST:event_jCheckBoxMaleActionPerformed

    private void jCheckBoxFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFemaleActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxFemale.isSelected() == true) // if check box is checked
        {
            jCheckBoxMale.setSelected(false);  // button will enable
            
        }
    }//GEN-LAST:event_jCheckBoxFemaleActionPerformed

    private void LectNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectNICActionPerformed

    private void LectQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectQualificationActionPerformed

    private void jButtonNextregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextregMouseClicked
        Staffmanage acc = new Staffmanage();
        acc.setVisible(true);
        acc.pack();
        acc.setLocationRelativeTo(null);
        acc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonNextregMouseClicked

    private void jButtonNextregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextregActionPerformed
        // TODO add your handling code here:
        String lecid = lectID.getText();
        String FirstName = LectFname.getText();
        String LastName = LectLname.getText();
        String nic = LectEmail.getText();
        String gender = "Male";
        if (jCheckBoxFemale.isSelected() == true) {
            gender = "Female";
        }

        String qualification = LectQualification.getText();
        String contact = LectContact.getText();
        String email = LectNIC.getText();
        String address = LectAddress.getText();
        

        try {

            if (Validation_Material() == true) {
                DbHandler.setData("INSERT INTO grup_project.lecturers(lecID,lecFName,lecLName,lecEmail,lecgender,lecqualification,leccontact,lecnic,lecaddress) values('" + lecid + "','" + FirstName + "','" + LastName + "','" + nic + "','" + gender + "','" + qualification + "','" + contact + "','" + email + "','" + address + "')");

                JOptionPane.showMessageDialog(null, "Values successfuly Inserted");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        LectFname.setText(null);
        lectID.setText(null);
        LectLname.setText(null);
        LectEmail.setText(null);
        LectQualification.setText(null);
        LectNIC.setText(null);
        LectAddress.setText(null);

    }//GEN-LAST:event_jButtonNextregActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            
        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }


    }//GEN-LAST:event_uploadActionPerformed

    private void LectContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectContactActionPerformed

    private void LectFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectFnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LectAddress;
    private javax.swing.JTextField LectContact;
    private javax.swing.JTextField LectEmail;
    private javax.swing.JTextField LectFname;
    private javax.swing.JTextField LectLname;
    private javax.swing.JTextField LectNIC;
    private javax.swing.JTextField LectQualification;
    private javax.swing.JButton jButtonNextreg;
    private javax.swing.JCheckBox jCheckBoxFemale;
    private javax.swing.JCheckBox jCheckBoxMale;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHomeback;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lectID;
    private javax.swing.JButton upload;
    private javax.swing.JLabel uploadfile;
    // End of variables declaration//GEN-END:variables
}
