/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import Connection.DbHandler;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    String savepath;

    public RegistrationForm() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    boolean Validation_Material() {

        java.util.Date dateForDatechhoser1 = StdDOB.getDate();

        if (stdtID.getText().isEmpty() || StdtLname.getText().isEmpty() || StdNIC.getText().isEmpty() || StdtContact.getText().isEmpty() || StdEmail.getText().isEmpty() || StdtAddress.getText().isEmpty() || dateForDatechhoser1 == null) {
            JOptionPane.showMessageDialog(null, "Please Insert values");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jLabelHomeback = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        stdtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StdNIC = new javax.swing.JTextField();
        StdtLname = new javax.swing.JTextField();
        jCheckBox2nd = new javax.swing.JCheckBox();
        jCheckBoxFemale = new javax.swing.JCheckBox();
        StdEmail = new javax.swing.JTextField();
        StdDOB = new com.toedter.calendar.JDateChooser();
        jButtonNextreg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StdtAddress = new javax.swing.JTextArea();
        upload = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        StdtFname = new javax.swing.JTextField();
        StdtContact = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxMale1 = new javax.swing.JCheckBox();
        jCheckBox1st = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name   :");

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT REGISTRATION FORM");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMini.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMini.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMini.setText("-");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });

        jLabelHomeback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHomeback.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_Back_30px.png"))); // NOI18N
        jLabelHomeback.setText("Back");
        jLabelHomeback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomebackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomeback, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMini)
                .addGap(27, 27, 27)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelHomeback)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMini))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Last Name  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 117, 31));

        stdtID.setBackground(new java.awt.Color(153, 153, 153));
        stdtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stdtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdtIDActionPerformed(evt);
            }
        });
        jPanel2.add(stdtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 255, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*First Name  ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Date of Birth");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 117, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*NIC No     ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 107, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Gender       ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 117, 31));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("*Intake  ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 117, 31));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address    ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BASIC INFORMATION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 213, -1));

        StdNIC.setBackground(new java.awt.Color(153, 153, 153));
        StdNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StdNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdNICActionPerformed(evt);
            }
        });
        jPanel2.add(StdNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 255, 31));

        StdtLname.setBackground(new java.awt.Color(153, 153, 153));
        StdtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StdtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdtLnameActionPerformed(evt);
            }
        });
        jPanel2.add(StdtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 255, 31));

        jCheckBox2nd.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox2nd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2nd.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2nd.setText("2nd(July)");
        jCheckBox2nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ndActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 100, 31));

        jCheckBoxFemale.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxFemale.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxFemale.setText("Female");
        jCheckBoxFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 81, 31));

        StdEmail.setBackground(new java.awt.Color(153, 153, 153));
        StdEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StdEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdEmailActionPerformed(evt);
            }
        });
        jPanel2.add(StdEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 255, 31));

        StdDOB.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(StdDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 255, 31));

        jButtonNextreg.setBackground(new java.awt.Color(34, 167, 240));
        jButtonNextreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNextreg.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNextreg.setText("Next");
        jButtonNextreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextregMouseClicked(evt);
            }
        });
        jButtonNextreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextregActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNextreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 89, 34));

        jButton1.setBackground(new java.awt.Color(207, 0, 15));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Email        ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, 31));

        StdtAddress.setColumns(20);
        StdtAddress.setRows(5);
        jScrollPane1.setViewportView(StdtAddress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 260, -1));

        upload.setText("Browse");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel2.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Student ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        StdtFname.setBackground(new java.awt.Color(153, 153, 153));
        StdtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StdtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdtFnameActionPerformed(evt);
            }
        });
        jPanel2.add(StdtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 255, 31));

        StdtContact.setBackground(new java.awt.Color(153, 153, 153));
        StdtContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StdtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdtContactActionPerformed(evt);
            }
        });
        jPanel2.add(StdtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 255, 31));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("*Contact No  ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, 117, 31));

        jCheckBoxMale1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxMale1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxMale1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMale1.setText("Male");
        jCheckBoxMale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMale1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 64, 31));

        jCheckBox1st.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1st.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1st.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1st.setText("1st(February)");
        jCheckBox1st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1stActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1st, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 120, 31));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 110, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdtIDActionPerformed

    private void StdNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdNICActionPerformed

    private void StdtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdtLnameActionPerformed

    private void jCheckBoxFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFemaleActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxFemale.isSelected() == true) // if check box is checked
        {
            jCheckBox2nd.setSelected(false);  // button will enable
            //btnOne.setText("Hi im enabled");// button text will change into parameter msg..
        }
    }//GEN-LAST:event_jCheckBoxFemaleActionPerformed

    private void StdEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdEmailActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jButtonNextregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextregActionPerformed
        // TODO add your handling code here:
        String sid = stdtID.getText();
        String FirstName = StdtFname.getText();
        String LastName = StdtLname.getText();
        String nic = StdNIC.getText();
        String gender = "Male";
        if (jCheckBoxFemale.isSelected() == true) {
            gender = "Female";
        }
        java.util.Date dateForDateChoser1 = StdDOB.getDate();
        String dob = String.format("%1$ty-%1$tm-%1$td", dateForDateChoser1);
        String contactNo = StdtContact.getText();
        String email = StdEmail.getText();
        String address = StdtAddress.getText();
        
        String intake = "1st(February)";
        if (jCheckBox2nd.isSelected() == true) {
            intake = "2nd(July)";
        }

        try {
            
            if (Validation_Material() == true) {
                DbHandler.setData("INSERT INTO grup_project.student(sid,fname,lname,nic,gender,dob,contact,email,address,intake) values('" + sid + "','" + FirstName + "','" + LastName + "','" + nic + "','" + gender + "','" + dob + "','" + contactNo + "','" + email + "','" + address + "','" + intake + "')");

                JOptionPane.showMessageDialog(null, "Values successfuly Inserted");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        stdtID.setText(null);
        StdtLname.setText(null);
        StdNIC.setText(null);
        StdtContact.setText(null);
        StdEmail.setText(null);
        StdtAddress.setText(null);
        StdDOB.setDate(null);
        MastersAcademic acc = new MastersAcademic();
        acc.setVisible(true);
        acc.pack();
        acc.setLocationRelativeTo(null);
        acc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonNextregActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonNextregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextregMouseClicked
                
    }//GEN-LAST:event_jButtonNextregMouseClicked

    private void jLabelHomebackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomebackMouseClicked
        Homef hm = new Homef();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHomebackMouseClicked

    private void jCheckBox2ndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ndActionPerformed

        if (jCheckBox2nd.isSelected() == true) // if check box is checked
        {
            jCheckBoxFemale.setSelected(false);  // button will enable
            
        }

    }//GEN-LAST:event_jCheckBox2ndActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Save Image");
            chooser.setFileFilter(new FileNameExtensionFilter("IMAGES ONLY", "png", "jpeg", "jpg")); //this file extentions are shown
            BufferedImage image = new BufferedImage(110, 150, BufferedImage.TRANSLUCENT);
            int showSaveDialog = chooser.showSaveDialog(this);
            String filePath = "D:\\Campus Stuff\\"
                    + "Assignment\\src\\ProfilePics";//chooser.getCurrentDirectory().toString().replace("\\", "/");
            String fileName = chooser.getSelectedFile().getName(); //get user entered file name to save
            ImageIO.write(image, "PNG", new File(filePath + "/" + fileName));

            if (showSaveDialog == JFileChooser.APPROVE_OPTION) {
                File selectedFile = chooser.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                jLabel4.setIcon(ResizeImage(path));
                savepath = path;

            }
        } catch (IOException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_uploadActionPerformed

    private void StdtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdtFnameActionPerformed

    private void StdtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StdtContactActionPerformed

    private void jCheckBoxMale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMale1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMale1ActionPerformed

    private void jCheckBox1stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1stActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser StdDOB;
    private javax.swing.JTextField StdEmail;
    private javax.swing.JTextField StdNIC;
    private javax.swing.JTextArea StdtAddress;
    private javax.swing.JTextField StdtContact;
    private javax.swing.JTextField StdtFname;
    private javax.swing.JTextField StdtLname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNextreg;
    private javax.swing.JCheckBox jCheckBox1st;
    private javax.swing.JCheckBox jCheckBox2nd;
    private javax.swing.JCheckBox jCheckBoxFemale;
    private javax.swing.JCheckBox jCheckBoxMale1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHomeback;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField stdtID;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables

}
