
import Connection.DbHandler;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class ViewInstructorDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewInstructorDetails
     */
    public ViewInstructorDetails() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 650));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. //
     * <editor-fold defaultstate="collapsed" desc="Generated Code">
     * private void initComponents() {
     *
     * jPanel2 = new javax.swing.JPanel(); jLabel2 = new javax.swing.JLabel();
     * jLabel7 = new javax.swing.JLabel(); jTextField1 = new
     * javax.swing.JTextField(); jButton1 = new javax.swing.JButton(); jLabel8 =
     * new javax.swing.JLabel(); jLabel9 = new javax.swing.JLabel(); jLabel10 =
     * new javax.swing.JLabel(); jLabel11 = new javax.swing.JLabel(); jLabel13 =
     * new javax.swing.JLabel(); jLabel15 = new javax.swing.JLabel(); jLabel16 =
     * new javax.swing.JLabel(); jLabel1 = new javax.swing.JLabel(); jLabel4 =
     * new javax.swing.JLabel(); jLabel5 = new javax.swing.JLabel(); jLabel17 =
     * new javax.swing.JLabel(); jLabel19 = new javax.swing.JLabel(); jLabel21 =
     * new javax.swing.JLabel(); jLabel22 = new javax.swing.JLabel();
     *
     * setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
     *
     * jPanel2.setBackground(new java.awt.Color(0, 0, 51));
     * jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
     *
     * jLabel2.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel2, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
     *
     * jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
     * jLabel7.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel7.setText("Instructor ID"); jPanel2.add(jLabel7, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, 100, 22));
     *
     * jTextField1.addActionListener(new java.awt.event.ActionListener() {
     * public void actionPerformed(java.awt.event.ActionEvent evt) {
     * jTextField1ActionPerformed(evt); } }); jPanel2.add(jTextField1, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, 124, -1));
     *
     * jButton1.setText("View"); jButton1.addActionListener(new
     * java.awt.event.ActionListener() { public void
     * actionPerformed(java.awt.event.ActionEvent evt) {
     * jButton1ActionPerformed(evt); } }); jPanel2.add(jButton1, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(267, 31, -1, -1));
     *
     * jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel8.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel8.setText("First Name :"); jPanel2.add(jLabel8, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 22));
     *
     * jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel9.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel9.setText("Gender :"); jPanel2.add(jLabel9, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, 22));
     *
     * jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel10.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel10.setText("Last Name :"); jPanel2.add(jLabel10, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 22));
     *
     * jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel11.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel11.setText("Email :"); jPanel2.add(jLabel11, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 76, 22));
     *
     * jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel13.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel13.setText("Qualifications:"); jPanel2.add(jLabel13, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 90, 22));
     *
     * jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel15.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel15.setText("NIC :"); jPanel2.add(jLabel15, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 90, 22));
     *
     * jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     * jLabel16.setForeground(new java.awt.Color(255, 255, 255));
     * jLabel16.setText("Address :"); jPanel2.add(jLabel16, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 90, 22));
     *
     * jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel1.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel1, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, 20));
     *
     * jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel4.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel4, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 30));
     *
     * jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel5.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel5, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, 20));
     *
     * jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel17.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel17, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 30));
     *
     * jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel19.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel19, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 290, 30));
     *
     * jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel21.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel21, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 240, 30));
     *
     * jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
     * jLabel22.setForeground(new java.awt.Color(255, 255, 255));
     * jPanel2.add(jLabel22, new
     * org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 210, 30));
     *
     * javax.swing.GroupLayout layout = new
     * javax.swing.GroupLayout(getContentPane());
     * getContentPane().setLayout(layout); layout.setHorizontalGroup(
     * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     * .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
     * layout.createSequentialGroup() .addGap(0, 0, Short.MAX_VALUE)
     * .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900,
     * javax.swing.GroupLayout.PREFERRED_SIZE)) ); layout.setVerticalGroup(
     * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     * .addGroup(layout.createSequentialGroup() .addContainerGap()
     * .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1310,
     * javax.swing.GroupLayout.PREFERRED_SIZE)
     * .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
     * );
     *
     * pack(); }// </editor-fold>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonViewIns = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelHomeback1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Instructor ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, 100, 22));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, 124, -1));

        jButtonViewIns.setText("View");
        jButtonViewIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewInsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonViewIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 31, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First Name :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 22));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender      :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 90, 22));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 22));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email         :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 76, 22));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Qualifications:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, 22));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NIC            :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 90, 22));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address      :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 90, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 200, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 150, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 290, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, 30));

        jPanel4.setBackground(new java.awt.Color(51, 0, 255));

        jLabelHomeback1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHomeback1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeback1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_Back_30px.png"))); // NOI18N
        jLabelHomeback1.setText("Back");
        jLabelHomeback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeback1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Instructor Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelHomeback1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272)
                .addComponent(jLabel6)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeback1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonViewInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewInsActionPerformed
        
        String InsID = jTextField1.getText();

        try {
            ResultSet rs = DbHandler.getData("select * from grup_project.instructors where insID='" + InsID + "'");

            while (rs.next()) {
                jLabel1.setText(rs.getString("insFName"));
                jLabel5.setText(rs.getString("insLName"));
                jLabel4.setText(rs.getString("insEmail"));
                jLabel17.setText(rs.getString("insgender"));
                jLabel19.setText(rs.getString("insQualifications"));
                jLabel21.setText(rs.getString("insnic"));
                jLabel22.setText(rs.getString("insaddress"));
            }

            rs.close();

        } catch (SQLException ex) {
            Logger.getLogger(ViewInstructorDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewInstructorDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewInsActionPerformed

    private void jLabelHomeback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeback1MouseClicked
        Staffmanage hm = new Staffmanage();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHomeback1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInstructorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInstructorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInstructorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInstructorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInstructorDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonViewIns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHomeback1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
